name: 'setup-protobuf'
description: 'Provide a description here'
author: 'izumin5210'
inputs:
  version:
    description: "Version of github.com/protocolbuffers/protobuf"
    default: 'v3.10.0'
runs:
  using: 'node12'
  main: 'lib/main.js'
